name: Frontend Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the frontend Docker image
      - name: Build Frontend Docker Image
        run: |
          docker build -t rudrprasad/resume:latest .

      # Push the frontend Docker image to Docker Hub
      - name: Push Frontend Docker Image
        run: |
          docker push rudrprasad/resume:latest
