name: Frontend Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the frontend Docker image
      - name: Build Frontend Docker Image
        run: |
          docker build -t rudrprasad/resume:latest .

      # Push the frontend Docker image to Docker Hub
      - name: Push Frontend Docker Image
        run: |
          docker push rudrprasad/resume:latest

      # SSH into EC2 and update the container
      - name: Deploy Frontend on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@44.204.76.51 'bash -s' << 'EOF'
          docker pull rudrprasad/resume:latest
          docker stop rudrprasad/resume || true
          docker rm frontend || true
          docker run -d --name frontend -p 3000:3000 rudrprasad/resume:latest
          EOF
